<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
 get_template_part( 'template-parts/contact-cta' ); ?>

<footer id="site-footer" role="contentinfo">
    <div class="container">
        <div class="footer-grid">

            <!-- Brand Column -->
            <div class="footer-brand">
                <div class="footer-logo">
                    <a href="<?php echo esc_url( home_url( '/' ) ); ?>">
                        <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=69,fit=crop/ALpeJ1OkE5HqbP9Z/ag-blue-mxB4r60XMEiBQ2EG.jpg"
                             alt="<?php bloginfo( 'name' ); ?>" height="44">
                    </a>
                </div>
                <p class="footer-tagline">
                    <?php esc_html_e( 'Leading provider of zero-emission energy solutions. Pioneering sustainable energy integration and advanced clean technology solutions.', 'amerigroup' ); ?>
                </p>
            </div>

            <!-- Quick Links -->
            <div class="footer-col">
                <h4><?php esc_html_e( 'Quick Links', 'amerigroup' ); ?></h4>
                <ul>
                    <li><a href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php esc_html_e( 'Home', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/about-us' ) ); ?>"><?php esc_html_e( 'About Us', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/technology-solution' ) ); ?>"><?php esc_html_e( 'Technology Solution', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/projects' ) ); ?>"><?php esc_html_e( 'Projects', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/our-team' ) ); ?>"><?php esc_html_e( 'Our Team', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/our-partners' ) ); ?>"><?php esc_html_e( 'Our Partners', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/activities' ) ); ?>"><?php esc_html_e( 'Activities', 'amerigroup' ); ?></a></li>
                </ul>
            </div>

            <!-- Solutions -->
            <div class="footer-col">
                <h4><?php esc_html_e( 'Solutions', 'amerigroup' ); ?></h4>
                <ul>
                    <li><a href="<?php echo esc_url( home_url( '/technology-solution' ) ); ?>"><?php esc_html_e( 'Hydrogen Systems', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/technology-solution' ) ); ?>"><?php esc_html_e( 'LNG Infrastructure', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/technology-solution' ) ); ?>"><?php esc_html_e( 'Renewable Energy', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/technology-solution' ) ); ?>"><?php esc_html_e( 'E-Mobility', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/technology-solution' ) ); ?>"><?php esc_html_e( 'Grid Modernization', 'amerigroup' ); ?></a></li>
                    <li><a href="<?php echo esc_url( home_url( '/projects' ) ); ?>"><?php esc_html_e( 'Projects', 'amerigroup' ); ?></a></li>
                </ul>
            </div>

            <!-- Offices -->
            <div class="footer-col">
                <h4><?php esc_html_e( 'Our Offices', 'amerigroup' ); ?></h4>

                <div class="footer-office">
                    <h5><?php esc_html_e( 'Hong Kong', 'amerigroup' ); ?></h5>
                    <p><?php esc_html_e( 'Unit 1201, Beverley Commercial Centre, 87–105 Chatham Rd. S. Tsim Sha Tsui, Kowloon', 'amerigroup' ); ?></p>
                </div>

                <div class="footer-office">
                    <h5><?php esc_html_e( 'Beijing, China', 'amerigroup' ); ?></h5>
                    <p><?php esc_html_e( 'Building A1, Zone B Daxing International Hydrogen Energy Demonstration Zone, Daxing District', 'amerigroup' ); ?></p>
                </div>

                <div class="footer-office">
                    <h5><?php esc_html_e( 'Vancouver, Canada', 'amerigroup' ); ?></h5>
                    <p><?php esc_html_e( '170 – 422 Richard St, Vancouver, BC, V6B 2Z4', 'amerigroup' ); ?></p>
                </div>
            </div>

        </div><!-- .footer-grid -->

        <div class="footer-bottom">
            <p>
                &copy; <?php echo esc_html( date( 'Y' ) ); ?>
                <a href="<?php echo esc_url( home_url('/') ); ?>" style="color:inherit;">
                    <?php bloginfo( 'name' ); ?>
                </a>.
                <?php esc_html_e( 'All rights reserved.', 'amerigroup' ); ?>
                &mdash;
                <?php esc_html_e( 'All content, branding, and assets are the exclusive intellectual property of Amerigroup International.', 'amerigroup' ); ?>
                <?php esc_html_e( 'Sourced from', 'amerigroup' ); ?>
                <a href="https://www.amerigroupint.net" style="color:inherit;" target="_blank" rel="noopener">www.amerigroupint.net</a>.
            </p>
            <p style="font-size:.78rem;opacity:.55;margin-top:4px;">
                <?php esc_html_e( 'WordPress theme produced by converting', 'amerigroup' ); ?>
                <a href="https://www.amerigroupint.net" style="color:inherit;" target="_blank" rel="noopener">amerigroupint.net</a>
                <?php esc_html_e( '— content and design © Amerigroup International.', 'amerigroup' ); ?>
            </p>
        </div>
    </div>
</footer>

<?php wp_footer(); ?>
</body>
</html>
