<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * Front Page — Amerigroup International v2
 * Fixes vs v1:
 *  - Second mid-page video (854238) added between services and feature images
 *  - Unsplash abstract building banner ("Leading Provider...") added before CTA
 *  - "As the urgency of the climate crisis..." paragraph restored
 *  - "Leading the Way Through Innovative Policies" subheading under Commitment
 */
get_header(); ?>

<!-- ============================================================
     HERO — Video 14588487 (alternative energy autumn)
     ============================================================ -->
<section class="hero" id="hero">
    <div class="hero-video-wrap">
        <video autoplay muted loop playsinline
               poster="https://images.pexels.com/videos/14588487/4-k-footage-4k-alternative-energy-autumn-14588487.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=630&w=1200">
            <source src="https://videos.pexels.com/video-files/14588487/14588487-uhd_2560_1440_30fps.mp4" type="video/mp4">
        </video>
    </div>
    <div class="hero-overlay"></div>
    <div class="container">
        <div class="hero-content">
            <span class="hero-tag"><?php esc_html_e('Zero-Emission Energy Solutions','amerigroup'); ?></span>
            <h1><em><?php esc_html_e('Pioneering Sustainable Energy Integration and Advanced Clean Technology Solutions','amerigroup'); ?></em></h1>
            <p><?php esc_html_e('Innovative Solutions for Sustainable Energy Projects and Infrastructure towards carbon neutrality.','amerigroup'); ?></p>
            <div class="btn-group">
                <a href="<?php echo esc_url(home_url('/technology-solution')); ?>" class="btn btn-primary"><?php esc_html_e('Explore Solutions','amerigroup'); ?></a>
                <a href="<?php echo esc_url(home_url('/about-us')); ?>" class="btn btn-outline"><?php esc_html_e('About Us','amerigroup'); ?></a>
            </div>
        </div>
    </div>
</section>

<!-- ============================================================
     INTRO — Global Energy Transition
     ============================================================ -->
<section class="section section-alt">
    <div class="container">
        <span class="section-label"><?php esc_html_e('Global Energy Transition','amerigroup'); ?></span>
        <h2 class="section-title" style="max-width:820px;">
            <?php esc_html_e('Leading the Global Energy Transition with Scalable, Science-Driven Innovation','amerigroup'); ?>
        </h2>
        <p class="section-lead" style="max-width:1000px;">
            <?php esc_html_e('Amerigroup International stands at the forefront of the clean energy revolution, delivering unparalleled expertise and turnkey solutions in hydrogen production and dispensing, methanol fuel cell power generation and range extenders, renewable energy generation with solar, wind turbines, and innovative water solar solutions, liquefied natural gas (LNG) infrastructure — including onshore regasification terminals, offshore Floating Storage and Regasification Units (FSRU), and international LNG supply logistics — as well as power grid modernization and power plant integration with new energy technologies around the globe.','amerigroup'); ?>
        </p>
        <!-- Paragraph present on live site -->
        <p class="section-lead" style="max-width:1000px;margin-top:20px;">
            <?php esc_html_e('As the urgency of the climate crisis becomes clearer, we support the development of technology innovations, emissions regulations, and policy pathways designed to enable a net-zero emissions future by 2050. By adhering to established frameworks and collaborative strategies, we aim to contribute to lasting solutions that drive progress in emissions reductions and clean energy transitions.','amerigroup'); ?>
        </p>

        <!-- Commitment section — exact heading structure from live -->
        <div style="margin-top:48px;">
            <h6 style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--ag-blue);margin-bottom:6px;">
                <?php esc_html_e('Our Commitment To Progress','amerigroup'); ?>
            </h6>
            <p style="font-weight:700;margin-bottom:8px;"><?php esc_html_e('Leading the Way Through Innovative Policies and Sustainable Practices','amerigroup'); ?></p>
            <p style="color:var(--ag-muted);max-width:1000px;">
                <?php esc_html_e("It's alarming to realize that over 70% of global warming emissions come from the energy sector. Annually, nearly 40 billion tons of carbon dioxide are released into the atmosphere by our global energy systems, driving us ever closer to critical climate thresholds. As economies around the world continue to grow and energy demands surge, this figure is expected to rise — unless we act decisively to transform how we generate and consume energy.",'amerigroup'); ?>
            </p>
        </div>

        <!-- Strategy section -->
        <div style="margin-top:40px;">
            <h6 style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--ag-blue);margin-bottom:4px;">
                <?php esc_html_e('Our Strategy','amerigroup'); ?>
            </h6>
            <h6 style="font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--ag-blue);margin-bottom:16px;">
                <?php esc_html_e('Advancing Impactful Solutions','amerigroup'); ?>
            </h6>
            <p style="color:var(--ag-muted);margin-bottom:20px;">
                <?php esc_html_e('As an organization driven by data and results, we focus on a singular goal: reducing carbon emissions. This immense task demands innovation and systemic change across multiple fronts. Our approach centers on four critical areas:','amerigroup'); ?>
            </p>
            <ul class="strategy-list">
                <li><?php esc_html_e('Shift the narrative to emphasize the scale of the challenge and the comprehensive nature of the solutions required.','amerigroup'); ?></li>
                <li><?php esc_html_e('Transform technology by providing a diverse array of affordable, carbon-free energy solutions such as advanced renewables, zero-carbon fuels, carbon capture, next-generation nuclear power, and geothermal energy.','amerigroup'); ?></li>
                <li><?php esc_html_e('Evolve business models to incorporate scalable, modular energy systems that can be rapidly deployed anywhere.','amerigroup'); ?></li>
                <li><?php esc_html_e('Influence policy to foster the development, demonstration, and widespread adoption of technologies and systems necessary to reach net-zero emissions by midcentury.','amerigroup'); ?></li>
            </ul>
        </div>
    </div>
</section>

<!-- ============================================================
     STATS BAR
     ============================================================ -->
<div class="stats-bar">
    <div class="container">
        <div class="stats-grid">
            <div><div class="stat-number">100<sup>+</sup></div><div class="stat-label"><?php esc_html_e('Experience','amerigroup'); ?></div></div>
            <div><div class="stat-number">30<sup>+</sup></div><div class="stat-label"><?php esc_html_e('Clients','amerigroup'); ?></div></div>
            <div><div class="stat-number">4.6B</div><div class="stat-label"><?php esc_html_e('Bcf DOE Approved','amerigroup'); ?></div></div>
            <div><div class="stat-number">2050</div><div class="stat-label"><?php esc_html_e('Net-Zero Target','amerigroup'); ?></div></div>
        </div>
    </div>
</div>

<!-- ============================================================
     SERVICES — Comprehensive Clean Energy Solutions
     ============================================================ -->
<section class="section">
    <div class="container">
        <div class="text-center" style="margin-bottom:56px;">
            <span class="section-label"><?php esc_html_e('What We Do','amerigroup'); ?></span>
            <h2 class="section-title"><?php esc_html_e('Comprehensive Clean Energy Solutions','amerigroup'); ?></h2>
        </div>
        <div class="services-grid">
            <?php
            $services = [
                ['⚡','Power Grid Modernization & Power Plant Integration in Mexico','Integrating hydrogen, methanol, and renewable energy into Mexico\'s power grids for stable, low-carbon electricity.'],
                ['☀️','Renewable Energy Generation: Solar, Wind Turbines & Water Solar Solutions','Scalable solar PV, wind, and floating solar arrays for grid-stable clean energy.'],
                ['💧','Hydrogen Production & Dispensing Systems','Modular electrolysis and blue hydrogen facilities for transportation and industry.'],
                ['🔋','Methanol Fuel Cell Power Generation & Range Extenders','Clean methanol fuel cells for off-grid, backup, and electric mobility applications.'],
                ['🚢','LNG Onshore Regasification & Infrastructure','State-of-the-art onshore LNG terminals with storage, vaporization, and pipeline injection.'],
                ['⛽','Offshore Floating Storage and Regasification Units (FSRU)','Agile, cost-effective offshore FSRU alternatives to land-based terminals.'],
                ['🌐','Overseas LNG Supply Chain Management','End-to-end LNG procurement, marine transport, and global distribution.'],
                ['🚛','E-Mobility Integration & Commercial Electric Vehicles','EV fleets, commercial electric trucks, and hydrogen fuel cell vehicles at scale.'],
            ];
            foreach($services as $s): ?>
            <div class="service-card">
                <div class="service-icon"><?php echo $s[0]; ?></div>
                <h3><?php echo esc_html($s[1]); ?></h3>
                <p><?php echo esc_html($s[2]); ?></p>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- ============================================================
     SECOND VIDEO — Video 854238 (live site mid-page video)
     ============================================================ -->
<div class="mid-video-section">
    <video autoplay muted loop playsinline
           poster="https://images.pexels.com/videos/854238/free-video-854238.jpg?auto=compress&cs=tinysrgb&fit=crop&h=630&w=1200">
        <source src="https://videos.pexels.com/video-files/854238/854238-hd_1280_720_30fps.mp4" type="video/mp4">
    </video>
    <div class="mid-video-overlay"></div>
    <div class="mid-video-content">
        <h2><?php esc_html_e('Pioneering the Future of Clean Energy','amerigroup'); ?></h2>
        <p><?php esc_html_e('From hydrogen and LNG to renewables and e-mobility — delivering integrated solutions at scale.','amerigroup'); ?></p>
    </div>
</div>

<!-- ============================================================
     THREE-UP FEATURE LINKS (About / Projects / Technology)
     ============================================================ -->
<section class="section-sm section-alt">
    <div class="container">
        <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:0;">
            <?php
            $features = [
                ['https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=538,fit=crop/ALpeJ1OkE5HqbP9Z/multiculture-2-AQEpwgjRPZUvv6Gk.jpg','About Us', home_url('/about-us')],
                ['https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=538,fit=crop/ALpeJ1OkE5HqbP9Z/h2-d95g2LPzZOT4zZzz.jpg','Project', home_url('/projects')],
                ['https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=553,fit=crop/ALpeJ1OkE5HqbP9Z/truck-electric-AVLbo2BXLxiqWZE7.jpg','Technology', home_url('/technology-solution')],
            ];
            foreach($features as $f): ?>
            <a href="<?php echo esc_url($f[2]); ?>" style="display:block;position:relative;overflow:hidden;">
                <img src="<?php echo esc_url($f[0]); ?>" alt="<?php echo esc_attr($f[1]); ?>"
                     style="width:100%;height:280px;object-fit:cover;display:block;transition:transform .5s ease;" loading="lazy">
                <div style="position:absolute;inset:0;background:rgba(0,30,70,.38);display:flex;align-items:flex-end;padding:24px;transition:background .3s ease;">
                    <span style="color:#fff;font-size:1.15rem;font-weight:700;text-decoration:underline;text-underline-offset:4px;">
                        <?php echo esc_html($f[1]); ?> →
                    </span>
                </div>
            </a>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- ============================================================
     UNSPLASH BANNER — "Leading Provider of Zero-Emission Energy Solutions"
     Exactly mirrors the live site section before the contact form
     ============================================================ -->
<div class="unsplash-banner">
    <div class="unsplash-banner-bg" style="background-image:url('https://images.unsplash.com/photo-1548248823-ce16a73b6d49?auto=format&fit=crop&w=1920');"></div>
    <div class="container" style="position:relative;z-index:2;width:100%;">
        <div class="unsplash-banner-content">
            <h2><?php esc_html_e('Leading Provider of Zero-Emission Energy Solutions','amerigroup'); ?></h2>
            <p><?php esc_html_e('Leading provider of zero-emission energy solutions.','amerigroup'); ?></p>
        </div>
    </div>
</div>

<?php get_footer(); ?>
