<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * Amerigroup International — functions.php
 * Theme setup, enqueue scripts/styles, register menus & widgets.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

define( 'AG_VERSION',    '2.0.0' );
define( 'AG_DIR',        get_template_directory() );
define( 'AG_URI',        get_template_directory_uri() );
define( 'AG_SOURCE_URL', 'https://www.amerigroupint.net' ); // Original site this theme was cloned from
define( 'AG_COPYRIGHT',  'Copyright (c) 2023-2025 Amerigroup International. All rights reserved.' );

/**
 * Inject copyright <meta> tags into every page <head>.
 * This makes the ownership and source URL visible to browsers,
 * crawlers, and anyone inspecting the page source.
 */
function ag_inject_copyright_meta() {
    echo "\n<!-- ============================================================\n";
    echo "     Amerigroup International — WordPress Theme v" . AG_VERSION . "\n";
    echo "     " . AG_COPYRIGHT . "\n";
    echo "     Original website : " . AG_SOURCE_URL . "\n";
    echo "     This WordPress theme was produced by mirroring and converting\n";
    echo "     the live site at " . AG_SOURCE_URL . " into a WordPress theme.\n";
    echo "     All content, copy, and assets remain the exclusive intellectual\n";
    echo "     property of Amerigroup International.\n";
    echo "     ============================================================ -->\n";
    echo '<meta name="copyright"    content="' . esc_attr( AG_COPYRIGHT ) . '">' . "\n";
    echo '<meta name="owner"        content="Amerigroup International">' . "\n";
    echo '<meta name="source-site"  content="' . esc_attr( AG_SOURCE_URL ) . '">' . "\n";
    echo '<meta name="theme-origin" content="Converted from ' . esc_attr( AG_SOURCE_URL ) . ' — all content © Amerigroup International">' . "\n";
    echo '<link rel="canonical"     href="' . esc_url( home_url( '/' ) ) . '">' . "\n\n";
}
add_action( 'wp_head', 'ag_inject_copyright_meta', 1 );

/* ---------------------------------------------------------------
   THEME SETUP
--------------------------------------------------------------- */
function ag_theme_setup() {
    load_theme_textdomain( 'amerigroup', AG_DIR . '/languages' );

    add_theme_support( 'title-tag' );
    add_theme_support( 'post-thumbnails' );
    add_theme_support( 'automatic-feed-links' );
    add_theme_support( 'html5', [ 'search-form','comment-form','comment-list','gallery','caption','script','style' ] );
    add_theme_support( 'custom-logo', [
        'height'      => 80,
        'width'       => 320,
        'flex-height' => true,
        'flex-width'  => true,
    ] );
    add_theme_support( 'customize-selective-refresh-widgets' );

    register_nav_menus( [
        'primary' => __( 'Primary Navigation', 'amerigroup' ),
        'footer'  => __( 'Footer Navigation',  'amerigroup' ),
    ] );

    add_image_size( 'ag-hero',    1920, 900, true );
    add_image_size( 'ag-card',    800,  500, true );
    add_image_size( 'ag-team',    400,  500, true );
    add_image_size( 'ag-partner', 320,  160, false );
}
add_action( 'after_setup_theme', 'ag_theme_setup' );

/* ---------------------------------------------------------------
   ENQUEUE ASSETS
--------------------------------------------------------------- */
function ag_enqueue_assets() {
    // Google Fonts
    wp_enqueue_style(
        'ag-fonts',
        'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap',
        [], null
    );

    // Main stylesheet
    wp_enqueue_style( 'ag-style', get_stylesheet_uri(), [ 'ag-fonts' ], AG_VERSION );

    // Main JS
    wp_enqueue_script( 'ag-main', AG_URI . '/assets/js/main.js', [], AG_VERSION, true );

    wp_localize_script( 'ag-main', 'agData', [
        'ajaxurl' => admin_url( 'admin-ajax.php' ),
        'nonce'   => wp_create_nonce( 'ag_contact_nonce' ),
    ] );
}
add_action( 'wp_enqueue_scripts', 'ag_enqueue_assets' );

/* ---------------------------------------------------------------
   CONTACT FORM AJAX HANDLER
--------------------------------------------------------------- */
function ag_handle_contact() {
    check_ajax_referer( 'ag_contact_nonce', 'nonce' );

    $name    = sanitize_text_field( $_POST['contact_name']  ?? '' );
    $email   = sanitize_email(      $_POST['contact_email'] ?? '' );
    $enquiry = sanitize_textarea_field( $_POST['contact_enquiry'] ?? '' );

    if ( ! $email || ! $enquiry ) {
        wp_send_json_error( [ 'message' => __( 'Please fill in all required fields.', 'amerigroup' ) ] );
    }

    $to      = get_option( 'admin_email' );
    $subject = sprintf( __( 'New Enquiry from %s — Amerigroup', 'amerigroup' ), $name ?: $email );
    $body    = "Name: {$name}\nEmail: {$email}\n\nMessage:\n{$enquiry}";
    $headers = [ "Reply-To: {$email}", 'Content-Type: text/plain; charset=UTF-8' ];

    $sent = wp_mail( $to, $subject, $body, $headers );

    if ( $sent ) {
        wp_send_json_success( [ 'message' => __( 'Thank you! We will be in touch shortly.', 'amerigroup' ) ] );
    } else {
        wp_send_json_error( [ 'message' => __( 'Sorry, there was an error. Please try again.', 'amerigroup' ) ] );
    }
}
add_action( 'wp_ajax_ag_contact',        'ag_handle_contact' );
add_action( 'wp_ajax_nopriv_ag_contact', 'ag_handle_contact' );

/* ---------------------------------------------------------------
   WIDGET AREAS
--------------------------------------------------------------- */
function ag_register_sidebars() {
    register_sidebar( [
        'name'          => __( 'Footer Column 1', 'amerigroup' ),
        'id'            => 'footer-1',
        'before_widget' => '<div class="footer-widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h4 class="widget-title">',
        'after_title'   => '</h4>',
    ] );
}
add_action( 'widgets_init', 'ag_register_sidebars' );

/* ---------------------------------------------------------------
   CUSTOM POST TYPE: TEAM MEMBER
--------------------------------------------------------------- */
function ag_register_cpt_team() {
    $labels = [
        'name'               => __( 'Team Members', 'amerigroup' ),
        'singular_name'      => __( 'Team Member',  'amerigroup' ),
        'add_new_item'       => __( 'Add New Team Member', 'amerigroup' ),
        'edit_item'          => __( 'Edit Team Member',    'amerigroup' ),
        'menu_name'          => __( 'Team',                'amerigroup' ),
    ];
    register_post_type( 'ag_team', [
        'labels'      => $labels,
        'public'      => true,
        'show_in_rest'=> true,
        'menu_icon'   => 'dashicons-groups',
        'supports'    => [ 'title', 'editor', 'thumbnail', 'excerpt', 'custom-fields' ],
        'rewrite'     => [ 'slug' => 'team' ],
    ] );
}
add_action( 'init', 'ag_register_cpt_team' );

/* ---------------------------------------------------------------
   CUSTOM POST TYPE: PARTNER
--------------------------------------------------------------- */
function ag_register_cpt_partner() {
    $labels = [
        'name'          => __( 'Partners', 'amerigroup' ),
        'singular_name' => __( 'Partner',  'amerigroup' ),
        'add_new_item'  => __( 'Add New Partner', 'amerigroup' ),
        'menu_name'     => __( 'Partners', 'amerigroup' ),
    ];
    register_post_type( 'ag_partner', [
        'labels'      => $labels,
        'public'      => false,
        'show_ui'     => true,
        'show_in_rest'=> true,
        'menu_icon'   => 'dashicons-networking',
        'supports'    => [ 'title', 'thumbnail', 'custom-fields' ],
    ] );
}
add_action( 'init', 'ag_register_cpt_partner' );

/* ---------------------------------------------------------------
   CUSTOM META BOXES
--------------------------------------------------------------- */
function ag_add_meta_boxes() {
    add_meta_box( 'ag_team_details', __( 'Team Member Details', 'amerigroup' ), 'ag_render_team_meta', 'ag_team', 'normal', 'high' );
}
add_action( 'add_meta_boxes', 'ag_add_meta_boxes' );

function ag_render_team_meta( $post ) {
    wp_nonce_field( 'ag_team_meta', 'ag_team_nonce' );
    $title    = get_post_meta( $post->ID, '_ag_team_title',    true );
    $linkedin = get_post_meta( $post->ID, '_ag_team_linkedin', true );
    ?>
    <table class="form-table">
        <tr>
            <th><label for="ag_team_title"><?php esc_html_e( 'Job Title', 'amerigroup' ); ?></label></th>
            <td><input type="text" id="ag_team_title" name="ag_team_title" value="<?php echo esc_attr( $title ); ?>" class="regular-text"></td>
        </tr>
        <tr>
            <th><label for="ag_team_linkedin"><?php esc_html_e( 'LinkedIn URL', 'amerigroup' ); ?></label></th>
            <td><input type="url" id="ag_team_linkedin" name="ag_team_linkedin" value="<?php echo esc_attr( $linkedin ); ?>" class="regular-text"></td>
        </tr>
    </table>
    <?php
}

function ag_save_team_meta( $post_id ) {
    if ( ! isset( $_POST['ag_team_nonce'] ) || ! wp_verify_nonce( $_POST['ag_team_nonce'], 'ag_team_meta' ) ) return;
    if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
    if ( ! current_user_can( 'edit_post', $post_id ) ) return;

    if ( isset( $_POST['ag_team_title'] ) )
        update_post_meta( $post_id, '_ag_team_title', sanitize_text_field( $_POST['ag_team_title'] ) );
    if ( isset( $_POST['ag_team_linkedin'] ) )
        update_post_meta( $post_id, '_ag_team_linkedin', esc_url_raw( $_POST['ag_team_linkedin'] ) );
}
add_action( 'save_post', 'ag_save_team_meta' );

/* ---------------------------------------------------------------
   BODY CLASSES
--------------------------------------------------------------- */
function ag_body_classes( $classes ) {
    if ( is_front_page() ) $classes[] = 'is-front-page';
    if ( is_page() )       $classes[] = 'page-' . get_post_field( 'post_name', get_the_ID() );
    return $classes;
}
add_action( 'body_class', 'ag_body_classes' );

/* ---------------------------------------------------------------
   TEMPLATE REDIRECT — map page slugs to templates
--------------------------------------------------------------- */
function ag_template_redirect( $template ) {
    if ( is_page() ) {
        $slug   = get_post_field( 'post_name', get_the_ID() );
        $lookup = AG_DIR . "/page-{$slug}.php";
        if ( file_exists( $lookup ) ) return $lookup;
    }
    return $template;
}
add_filter( 'template_include', 'ag_template_redirect' );
