<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="profile" href="https://gmpg.org/xfn/11">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>

<header id="site-header" role="banner">
    <div class="container">
        <div class="header-inner">

            <a href="<?php echo esc_url( home_url( '/' ) ); ?>" class="site-logo" aria-label="<?php bloginfo( 'name' ); ?>">
                <?php
                if ( has_custom_logo() ) :
                    the_custom_logo();
                else :
                    ?>
                    <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,fit=crop,q=95/ALpeJ1OkE5HqbP9Z/ag-blue-mxB4r60XMEiBQ2EG.jpg"
                         alt="<?php bloginfo( 'name' ); ?>" height="48">
                <?php endif; ?>
            </a>

            <nav class="primary-nav" id="primary-nav" role="navigation" aria-label="<?php esc_attr_e( 'Primary Menu', 'amerigroup' ); ?>">
                <?php
                wp_nav_menu( [
                    'theme_location' => 'primary',
                    'menu_class'     => '',
                    'container'      => false,
                    'fallback_cb'    => 'ag_fallback_nav',
                ] );
                ?>
            </nav>

            <button class="nav-toggle" id="nav-toggle" aria-controls="primary-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span></span><span></span><span></span>
            </button>

        </div>
    </div>
</header>
<?php

function ag_fallback_nav() {
    $pages = [
        ''                    => 'Home',
        'about-us'            => 'About Us',
        'technology-solution' => 'Technology Solution',
        'projects'            => 'Projects',
        'our-team'            => 'Our Team',
        'our-partners'        => 'Our Partners',
        'activities'          => 'Activities',
    ];
    echo '<ul>';
    foreach ( $pages as $slug => $label ) {
        $url     = $slug ? home_url( '/' . $slug ) : home_url( '/' );
        $current = ( $slug === '' && is_front_page() ) || ( $slug && is_page( $slug ) ) ? ' class="current-menu-item"' : '';
        printf( '<li%s><a href="%s">%s</a></li>', $current, esc_url( $url ), esc_html( $label ) );
    }
    echo '</ul>';
}
