<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * The main template file — fallback for WordPress.
 */
get_header();

if ( is_home() || is_front_page() ) {
    get_template_part( 'front-page' );
} else {
    ?>
    <section class="section">
        <div class="container">
            <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
                <h1><?php the_title(); ?></h1>
                <div class="entry-content"><?php the_content(); ?></div>
            <?php endwhile; endif; ?>
        </div>
    </section>
    <?php
}

get_footer();
