<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
 get_header(); ?>

<section class="page-hero">
    <div class="page-hero-video">
        <div class="page-hero-fallback" style="background-image:url('https://images.unsplash.com/photo-1548248823-ce16a73b6d49?auto=format&fit=crop&w=1920');"></div>
        <video autoplay muted loop playsinline
               poster="https://images.unsplash.com/photo-1548248823-ce16a73b6d49?auto=format&fit=crop&w=1920">
            <source src="https://videos.pexels.com/video-files/854238/854238-hd_1280_720_30fps.mp4" type="video/mp4">
        </video>
    </div>
    <div class="page-hero-overlay"></div>
    <div class="container">
        <div class="page-hero-content">
            <p class="breadcrumb">
                <a href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Home','amerigroup'); ?></a>
                &rsaquo; <?php the_title(); ?>
            </p>
            <h1><?php the_title(); ?></h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container" style="max-width:800px;">
        <?php while ( have_posts() ) : the_post(); ?>
            <div class="entry-content">
                <?php the_content(); ?>
            </div>
        <?php endwhile; ?>
    </div>
</section>

<?php get_footer();
