<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * Template Name: About Us — v2
 * Fixes vs v1:
 *  - Added Amerigroup logo strip image (c843a283) after hero, linking to home — matches live
 *  - Stat labels fixed: "Experience" (not "Years Experience") and "Clients" — exact live labels
 *  - Values section: each value now has its own photo from live site (rocket, clean-energy, multiculture, mountain-top)
 */
get_header(); ?>

<!-- HERO VIDEO -->
<section class="page-hero">
    <div class="page-hero-video">
        <div class="page-hero-fallback" style="background-image:url('https://images.pexels.com/videos/5756264/australia-beach-broken-head-coast-5756264.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920');"></div>
        <video autoplay muted loop playsinline
               poster="https://images.pexels.com/videos/5756264/australia-beach-broken-head-coast-5756264.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920">
            <source src="https://videos.pexels.com/video-files/5756264/5756264-uhd_3840_2160_30fps.mp4" type="video/mp4">
        </video>
    </div>
    <div class="page-hero-overlay"></div>
    <div class="container">
        <div class="page-hero-content">
            <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Home','amerigroup'); ?></a> &rsaquo; <?php esc_html_e('About Us','amerigroup'); ?></p>
            <h1><strong><?php esc_html_e('Leading the way through innovative policies and sustainable practices','amerigroup'); ?></strong></h1>
        </div>
    </div>
</section>

<!-- LOGO STRIP — matches live site (second logo display after hero) -->
<div class="about-logo-strip" style="padding:28px 0 0;background:var(--ag-white);">
    <a href="<?php echo esc_url(home_url('/')); ?>">
        <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=91,fit=crop/ALpeJ1OkE5HqbP9Z/c843a283-57a5-4f59-b1c0-499c1b8f7c83_1_105_c-Yan1Z1O96WtnB58W.jpeg"
             alt="<?php bloginfo('name'); ?>" style="height:70px;width:auto;" loading="lazy">
    </a>
</div>

<!-- MISSION -->
<section class="section">
    <div class="container">
        <div class="about-split">
            <div class="about-split-img">
                <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=538,fit=crop/ALpeJ1OkE5HqbP9Z/multiculture-2-AQEpwgjRPZUvv6Gk.jpg"
                     alt="<?php esc_attr_e('Amerigroup team','amerigroup'); ?>" loading="lazy">
            </div>
            <div class="about-split-body">
                <span class="section-label"><?php esc_html_e('Our Mission','amerigroup'); ?></span>
                <h2><?php esc_html_e('Dedicated to Leading the Transition to Clean Energy','amerigroup'); ?></h2>
                <p><?php esc_html_e('At Amerigroup, we are dedicated to leading the transition to clean energy by providing zero-emission solutions for transportation and energy production. Our mission is to reduce greenhouse gas emissions, improve the quality of energy supply, and support sustainable regional development.','amerigroup'); ?></p>

                <!-- Stats — EXACT labels from live site: "Experience" and "Clients" -->
                <div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:32px;">
                    <div style="text-align:center;background:var(--ag-blue-light);padding:28px 20px;border-radius:12px;">
                        <div style="font-size:2.2rem;font-weight:800;color:var(--ag-blue);">100<sup style="font-size:.9rem;">+</sup></div>
                        <!-- Live site label: "Experience" NOT "Years Experience" -->
                        <div style="font-size:.82rem;color:var(--ag-muted);text-transform:uppercase;letter-spacing:.08em;margin-top:4px;"><?php esc_html_e('Experience','amerigroup'); ?></div>
                    </div>
                    <div style="text-align:center;background:var(--ag-blue-light);padding:28px 20px;border-radius:12px;">
                        <div style="font-size:2.2rem;font-weight:800;color:var(--ag-blue);">30<sup style="font-size:.9rem;">+</sup></div>
                        <div style="font-size:.82rem;color:var(--ag-muted);text-transform:uppercase;letter-spacing:.08em;margin-top:4px;"><?php esc_html_e('Clients','amerigroup'); ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- HISTORY -->
<section class="section section-alt">
    <div class="container">
        <div class="about-split">
            <div class="about-split-body">
                <span class="section-label"><?php esc_html_e('Our History','amerigroup'); ?></span>
                <h2><?php esc_html_e('From Regional LNG Transporter to Global Green Energy Leader','amerigroup'); ?></h2>
                <p><?php esc_html_e('Amerigroup has grown from a regional LNG transporter to a global leader in green energy solutions. Over the past few decades, we have expanded our expertise to include hydrogen production, power grid modernization projects, and advanced clean energy infrastructure, consistently pushing the boundaries of innovation and sustainability. This legacy of growth fuels our commitment to meet today\'s climate and energy challenges with proven, integrated, and forward-thinking solutions.','amerigroup'); ?></p>
                <p style="margin-top:16px;"><?php esc_html_e('Amerigroup envisions a future where clean energy systems are seamlessly integrated across sectors, enabling sustainable industrial growth, resilient communities, and zero-emission transportation networks. Through relentless innovation, robust partnerships, and uncompromising operational excellence, we empower clients and governments to lead the global climate agenda.','amerigroup'); ?></p>
            </div>
            <div class="about-split-img">
                <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=550,fit=crop/ALpeJ1OkE5HqbP9Z/clean-energy-2-A0xV6DjeVJf1gxyv.jpg"
                     alt="<?php esc_attr_e('Clean Energy','amerigroup'); ?>" loading="lazy">
            </div>
        </div>
    </div>
</section>

<!-- VALUES — each with its exact photo from live site -->
<section class="section">
    <div class="container">
        <div class="text-center" style="margin-bottom:56px;">
            <span class="section-label"><?php esc_html_e('Core Values','amerigroup'); ?></span>
            <h2 class="section-title"><?php esc_html_e('Our Values','amerigroup'); ?></h2>
            <p class="section-lead"><?php esc_html_e('Leading the transition to clean energy with zero-emission solutions.','amerigroup'); ?></p>
        </div>

        <div class="values-grid">
            <?php
            /* Each value uses the EXACT Zyrosite/Unsplash image from the live site */
            $values = [
                [
                    'img'  => 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=503&h=360',
                    'alt'  => 'rocket ship launching during daytime',
                    'head' => 'Innovation',
                    'body' => 'Continuously pursuing new technologies and solutions',
                ],
                [
                    'img'  => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=550,fit=crop/ALpeJ1OkE5HqbP9Z/clean-energy-2-A0xV6DjeVJf1gxyv.jpg',
                    'alt'  => 'Clean energy',
                    'head' => 'Sustainability',
                    'body' => 'Committed to reducing environmental impact and promoting clean energy',
                ],
                [
                    'img'  => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=550,fit=crop/ALpeJ1OkE5HqbP9Z/multiculture-A1aJWMl2ROh5WwRb.jpg',
                    'alt'  => 'Multiculture team',
                    'head' => 'Regional Development',
                    'body' => 'Enhancing local economies through sustainable energy projects and infrastructure',
                ],
                [
                    'img'  => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=550,fit=crop/ALpeJ1OkE5HqbP9Z/mountain-top-dWxboR07E3HBev7b.jpg',
                    'alt'  => 'Mountain top',
                    'head' => 'Excellence',
                    'body' => 'Striving for the highest standards in all our operations',
                ],
            ];
            foreach($values as $v): ?>
            <div class="value-card-photo">
                <div class="value-card-photo-img">
                    <img src="<?php echo esc_url($v['img']); ?>" alt="<?php echo esc_attr($v['alt']); ?>" loading="lazy">
                </div>
                <div class="value-card-photo-body">
                    <h3><?php echo esc_html($v['head']); ?></h3>
                    <p><?php echo esc_html($v['body']); ?></p>
                    <div style="font-size:1.2rem;margin-top:8px;color:var(--ag-blue);">→</div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<?php get_footer(); ?>
