<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * Template Name: Technology Solution — v2
 * Fixes vs v1:
 *  - Intro H2 image (h2-d95g2LPzZOT4zZzz) added at top BEFORE first section — matches live
 *  - Exact content order mirrors live: Renewable → Hydrogen → Methanol → [img] → Power Grid → [img] → E-Mobility → Linear Generator → [img] → H2 Reactor → [img] → LNG Onshore → FSRU → LNG Supply Chain → [img]
 *  - Each section's image is the EXACT Zyrosite asset from live (not generic placeholders)
 *  - Bottom gallery added: lng-vessel + 0-emission badge + clean-energy-2
 *  - "Innovative Solutions" caption bar added before gallery
 */
get_header(); ?>

<section class="page-hero">
    <div class="page-hero-video">
        <div class="page-hero-fallback" style="background-image:url('https://images.pexels.com/videos/3130284/free-video-3130284.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920');"></div>
        <video autoplay muted loop playsinline
               poster="https://images.pexels.com/videos/3130284/free-video-3130284.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920">
            <source src="https://videos.pexels.com/video-files/3130284/3130284-uhd_3840_2160_30fps.mp4" type="video/mp4">
        </video>
    </div>
    <div class="page-hero-overlay"></div>
    <div class="container">
        <div class="page-hero-content">
            <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Home','amerigroup'); ?></a> &rsaquo; <?php esc_html_e('Technology Solution','amerigroup'); ?></p>
            <h1><?php esc_html_e('Innovative Solutions for Sustainable Energy Generation and Fuel Efficiency','amerigroup'); ?></h1>
            <p class="page-hero-sub"><?php esc_html_e('Enhancing fuel efficiency, reducing emissions, pioneering sustainable energy generation technology.','amerigroup'); ?></p>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <!-- TOP INTRO IMAGE — exact asset from live site, shown before first section title -->
        <div style="margin-bottom:56px;border-radius:12px;overflow:hidden;">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=254,fit=crop/ALpeJ1OkE5HqbP9Z/h2-d95g2LPzZOT4zZzz.jpg"
                 alt="<?php esc_attr_e('Hydrogen infrastructure','amerigroup'); ?>"
                 style="width:100%;height:320px;object-fit:cover;" loading="lazy">
        </div>

        <!-- 1. RENEWABLE ENERGY — no image on left in live, text-first -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('Renewable Energy Generation: Solar, Wind Turbines & Water Solar Solutions','amerigroup'); ?></h2>
                <p><?php esc_html_e('Amerigroup integrates cutting-edge solar photovoltaic systems, utility-scale wind turbines, and innovative water solar solutions such as floating solar arrays to maximize clean energy production. These renewables are designed to complement our portfolio, providing scalable, flexible power generation that supports grid stability and complements hydrogen and methanol fuel cell systems for a balanced, sustainable energy mix.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- 2. HYDROGEN PRODUCTION -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('Hydrogen Production & Dispensing Systems','amerigroup'); ?></h2>
                <p><?php esc_html_e('Harnessing cutting-edge electrolysis and blue hydrogen technologies with carbon capture, Amerigroup designs and deploys modular, scalable hydrogen production facilities. Our hydrogen refueling stations are engineered for industrial, transportation, and power generation applications — empowering the shift towards a zero-carbon hydrogen economy.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- 3. METHANOL FUEL CELL -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('Methanol Fuel Cell Power Generation & Range Extenders','amerigroup'); ?></h2>
                <p><?php esc_html_e('We deliver industry-leading methanol fuel cell generators and range extender systems, providing clean, reliable power for off-grid locations, emergency backup, and electric mobility. Our innovative methanol solutions combine efficiency, portability, and environmental performance, enabling seamless energy access in diverse operational contexts.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- IMAGE between Methanol and Power Grid — exact fd770447 asset from live -->
        <div style="margin:40px 0;border-radius:12px;overflow:hidden;">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=253,fit=crop,trim=170.52631578947367;0;97.44360902255639;423.3165829145729/ALpeJ1OkE5HqbP9Z/fd770447-8112-4c79-ae44-5808a9a98601-AQEZ11VJJ4Hpx847.jpeg"
                 alt="<?php esc_attr_e('Methanol fuel cell','amerigroup'); ?>"
                 style="width:100%;max-height:320px;object-fit:cover;" loading="lazy">
        </div>

        <!-- 4. POWER GRID MEXICO -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('Power Grid Modernization & Power Plant Integration in Mexico','amerigroup'); ?></h2>
                <p><?php esc_html_e('With extensive experience in Mexico\'s energy sector, Amerigroup spearheads power grid modernization projects that incorporate advanced clean energy technologies. Our services include integration of hydrogen and methanol fuel cells, renewables, and energy storage solutions into existing and new power plants, enabling reliable, flexible, and low-carbon electricity generation. This holistic approach optimizes grid stability, enhances renewable penetration, and supports Mexico\'s ambitious decarbonization goals.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- IMAGE between Power Grid and E-Mobility — exact b1db89fa asset from live -->
        <div style="margin:40px 0;border-radius:12px;overflow:hidden;">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=253,fit=crop,trim=120.3157894736842;0;68.75187969924812;516.8807339449542/ALpeJ1OkE5HqbP9Z/b1db89fa-e405-4eef-be62-00ba5ef1dd70-mxBXQByPElSyMMl6.jpeg"
                 alt="<?php esc_attr_e('Power grid','amerigroup'); ?>"
                 style="width:100%;max-height:320px;object-fit:cover;" loading="lazy">
        </div>

        <!-- 5. E-MOBILITY -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('E-Mobility Integration & Commercial Electric Vehicles','amerigroup'); ?></h2>
                <p><?php esc_html_e('Complementing our clean fuel technologies, Amerigroup champions the electrification of transport through comprehensive e-mobility solutions. This includes advanced electric vehicle (EV) fleets, commercial electric trucks, and cutting-edge hydrogen fuel cell vehicles, supported by scalable EV charging infrastructure designed for efficiency, interoperability, and future-proof grid integration.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- 6. ADVANCED LINEAR GENERATOR -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('Advanced Linear Generator Technology','amerigroup'); ?></h2>
                <p><?php esc_html_e('At the forefront of sustainable energy generation, this technology converts mechanical energy directly into electrical power with minimal moving parts. By employing a linear motion mechanism rather than traditional rotating components, this generator offers enhanced efficiency, longer operational lifespans, and greater reliability. Its compact design and scalability make it suitable for a wide range of applications, from distributed energy systems to grid support and emergency power supply, ensuring resilient and consistent energy output.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- IMAGE between Linear Generator and H2 Reactor — truck-electric asset -->
        <div style="margin:40px 0;border-radius:12px;overflow:hidden;">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=255,fit=crop/ALpeJ1OkE5HqbP9Z/truck-electric-AVLbo2BXLxiqWZE7.jpg"
                 alt="<?php esc_attr_e('Electric truck','amerigroup'); ?>"
                 style="width:100%;max-height:320px;object-fit:cover;" loading="lazy">
        </div>

        <!-- 7. HYDROGEN INJECTION REACTOR -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><strong><?php esc_html_e('Hydrogen Injection Reactor','amerigroup'); ?></strong></h2>
                <p><?php esc_html_e('A cutting-edge system designed to enhance fuel efficiency and reduce emissions in transport units by using only water as the source for hydrogen production. The reactor utilizes electrolysis to generate hydrogen on-demand, which is directly injected into the engine\'s combustion chamber. This seamless integration with existing engines results in optimized performance, cleaner fuel combustion, and reduced reliance on fossil fuels. The system is engineered for durability, low maintenance, and adaptability across different vehicle platforms.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- IMAGE between H2 Reactor and LNG — truck-engine asset -->
        <div style="margin:40px 0;border-radius:12px;overflow:hidden;">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=258,fit=crop/ALpeJ1OkE5HqbP9Z/truck-engine-AQEpwr1v06ix3Z3q.webp"
                 alt="<?php esc_attr_e('Truck engine','amerigroup'); ?>"
                 style="width:100%;max-height:320px;object-fit:cover;" loading="lazy">
        </div>

        <!-- 8. LNG ONSHORE REGASIFICATION -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('LNG Onshore Regasification & Infrastructure','amerigroup'); ?></h2>
                <p><?php esc_html_e('Amerigroup operates state-of-the-art onshore LNG regasification terminals designed for optimal throughput, safety, and integration with downstream gas networks. Our infrastructure services encompass LNG storage, vaporization, pipeline injection, and comprehensive logistics, facilitating secure and flexible natural gas supply for utilities and industries.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- 9. FSRU -->
        <div class="tech-item">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('Offshore Floating Storage and Regasification Units (FSRU)','amerigroup'); ?></h2>
                <p><?php esc_html_e('Our advanced offshore FSRU solutions offer agile, cost-effective alternatives to traditional land-based terminals. Strategically deployed in ports and coastal hubs worldwide, Amerigroup\'s FSRUs accelerate LNG import capacity with minimal environmental footprint and rapid commissioning timelines, addressing urgent energy demands with unmatched reliability.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- 10. OVERSEAS LNG SUPPLY CHAIN -->
        <div class="tech-item" style="border-bottom:none;">
            <div class="tech-item-body" style="grid-column:1/-1;">
                <h2><?php esc_html_e('Overseas LNG Supply Chain Management','amerigroup'); ?></h2>
                <p><?php esc_html_e('Amerigroup ensures end-to-end LNG supply chain excellence from international procurement, marine transportation, and cargo handling to distribution and delivery underpinned by rigorous safety standards and real-time monitoring systems. Our global reach and strategic partnerships guarantee dependable LNG sourcing tailored to market needs.','amerigroup'); ?></p>
            </div>
        </div>

        <!-- IMAGE after LNG Supply Chain — 36f2a920 asset from live -->
        <div style="margin:40px 0 0;border-radius:12px;overflow:hidden;">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=253,fit=crop,trim=157.89473684210526;0;90.22556390977444;519.4120481927711/ALpeJ1OkE5HqbP9Z/36f2a920-0115-4758-b76c-039deceea9bc-AMq8GG9XjnF5o7ge.jpeg"
                 alt="<?php esc_attr_e('LNG vessel','amerigroup'); ?>"
                 style="width:100%;max-height:320px;object-fit:cover;" loading="lazy">
        </div>

    </div><!-- /.container -->
</section>

<!-- ============================================================
     BOTTOM GALLERY — matches live site "Innovative Solutions" section
     3 images: lng-vessel + 0-emission + clean-energy-2
     ============================================================ -->
<div style="background:var(--ag-offwhite);padding:16px 0 0;">
    <div class="container">
        <div class="text-center" style="padding:40px 0 24px;">
            <span class="section-label"><?php esc_html_e('Innovative Solutions','amerigroup'); ?></span>
            <p style="color:var(--ag-muted);margin-top:8px;"><?php esc_html_e('Enhancing fuel efficiency, reducing emissions, pioneering sustainable energy generation technology.','amerigroup'); ?></p>
        </div>
    </div>
    <div class="tech-gallery">
        <div class="tech-gallery-item">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=738,fit=crop/ALpeJ1OkE5HqbP9Z/lng-vessel-dJo4zyEraNuMjjGg.jpg"
                 alt="<?php esc_attr_e('LNG vessel','amerigroup'); ?>" loading="lazy">
            <div class="tech-gallery-caption"><p><?php esc_html_e('LNG Vessel Operations','amerigroup'); ?></p></div>
        </div>
        <div class="tech-gallery-item">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=674,fit=crop,trim=13.869863013698629;0;13.869863013698629;0/ALpeJ1OkE5HqbP9Z/0-emission-m2WQJ3rNz8i98L1R.jpg"
                 alt="<?php esc_attr_e('Zero emission','amerigroup'); ?>" loading="lazy">
            <div class="tech-gallery-caption"><p><?php esc_html_e('Zero-Emission Commitment','amerigroup'); ?></p></div>
        </div>
        <div class="tech-gallery-item">
            <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=740,fit=crop/ALpeJ1OkE5HqbP9Z/clean-energy-2-A0xV6DjeVJf1gxyv.jpg"
                 alt="<?php esc_attr_e('Clean energy','amerigroup'); ?>" loading="lazy">
            <div class="tech-gallery-caption"><p><?php esc_html_e('Clean Energy Infrastructure','amerigroup'); ?></p></div>
        </div>
    </div>
</div>

<?php get_footer(); ?>
