<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * Template Name: Our Team — v2
 * Fixes vs v1:
 *  - Intro text structure matches live exactly: italic "thrives on individuality..." + bold sentence + "Our Team" heading + two bullet points
 *  - Ken Wong title on live: "Corporate Vice President" (not "Corporate Vice President & Co-Founder")
 *  - All profile photo URLs verified against live source
 */
get_header(); ?>

<section class="page-hero">
    <div class="page-hero-video">
        <div class="page-hero-fallback" style="background-image:url('https://images.pexels.com/videos/3255275/free-video-3255275.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920');"></div>
        <video autoplay muted loop playsinline
               poster="https://images.pexels.com/videos/3255275/free-video-3255275.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920">
            <source src="https://videos.pexels.com/video-files/3255275/3255275-uhd_3840_2160_25fps.mp4" type="video/mp4">
        </video>
    </div>
    <div class="page-hero-overlay"></div>
    <div class="container">
        <div class="page-hero-content">
            <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Home','amerigroup'); ?></a> &rsaquo; <?php esc_html_e('Our Team','amerigroup'); ?></p>
            <h1><?php esc_html_e('Our Team','amerigroup'); ?></h1>
        </div>
    </div>
</section>

<!-- INTRO — exact structure from live site -->
<section class="section-sm section-alt">
    <div class="container text-center" style="max-width:820px;">
        <!-- Live site uses: italic "thrives on individuality" + bold partner sentence -->
        <p style="font-size:1.1rem;margin-bottom:12px;">
            <em><?php esc_html_e('thrives on individuality and innovation.','amerigroup'); ?></em>
            &nbsp;<strong><?php esc_html_e('We bring firsthand experience from collaborations with industry-leading clients and premier business partners, underscoring our commitment to excellence.','amerigroup'); ?></strong>
        </p>
        <p style="font-size:1.25rem;font-weight:700;font-style:italic;color:var(--ag-blue);margin-bottom:20px;">
            <?php esc_html_e('Our Team','amerigroup'); ?>
        </p>
        <ul style="list-style:none;display:flex;flex-direction:column;gap:10px;text-align:left;max-width:620px;margin:0 auto;">
            <li style="font-style:italic;font-weight:600;">
                <?php esc_html_e('from engineering and project management to business development and operations','amerigroup'); ?>
            </li>
            <li style="font-style:italic;font-weight:600;">
                <?php esc_html_e('ensuring every unique perspective drives our success in advancing sustainable energy solutions','amerigroup'); ?>
            </li>
        </ul>
    </div>
</section>

<section class="section">
    <div class="container">
        <?php
        $team_query = new WP_Query(['post_type'=>'ag_team','posts_per_page'=>-1,'orderby'=>'menu_order','order'=>'ASC']);
        if($team_query->have_posts()):
            echo '<div class="team-grid">';
            while($team_query->have_posts()): $team_query->the_post();
                $job_title = get_post_meta(get_the_ID(),'_ag_team_title',true); ?>
                <div class="team-card">
                    <div class="team-card-photo"><?php if(has_post_thumbnail()) the_post_thumbnail('ag-team',['alt'=>get_the_title()]); ?></div>
                    <div class="team-card-body">
                        <h3><?php the_title(); ?></h3>
                        <?php if($job_title): ?><div class="team-title"><?php echo esc_html($job_title); ?></div><?php endif; ?>
                        <p><?php the_excerpt(); ?></p>
                    </div>
                </div>
            <?php endwhile; wp_reset_postdata();
            echo '</div>';
        else:
        // VERIFIED exact data from live site (all names, titles, bios, photo URLs confirmed)
        $team = [
            [
                'name'  => 'Mr. Gerardo Payán Ramos',
                'title' => 'President, Amerigroup International | President & Founder, AmerigroupLNG | Founder of AmeriGas Propane S.A. de C.V.',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=372,fit=crop/ALpeJ1OkE5HqbP9Z/gerardo-AMq1wbMMPPCw9jMO.png',
                'bio'   => 'Mr. Gerardo Payán Ramos serves as President in Amerigroup International, Founder and CEO of AmerigroupLNG, as well as the founder of AmeriGas Propane S.A. de C.V. in Mexico. With over 15 years in the energy industry, he is steering these companies toward becoming leading global providers of integrated energy solutions. His journey began as a consultant for Coca-Cola bottling companies across Latin America. Specializing in government relations and strategic partnerships between Mexico and the USA, Gerardo has become an authority in emerging energy fields — ranging from LNG and hydrogen to solar, wind, and EV conversion.',
            ],
            [
                'name'  => 'Mr. Ken Wong',
                // CONFIRMED from live: "Corporate Vice President" only — no "&Co-Founder" in bold title
                'title' => 'Corporate Vice President',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=498,fit=crop/ALpeJ1OkE5HqbP9Z/2a558d56-d2fc-4d43-bfb4-919e12915567_1_105_c-Y4LD2xoO5ESJDEXB.jpeg',
                'bio'   => 'Mr. Ken Wong, a Canadian-Chinese entrepreneur, serves as Corporate Vice President and Co-Founder of Amerigroup International, where he directs the company\'s global strategy and operations. His entrepreneurial journey spans commodity trading and mining across Canada, the USA, and Mexico. Notably, in 2012, he became the first Canadian-Chinese exporter of iron ore from Mexico to China — a milestone recognized by SGS. Since 2016, he has played a significant role in Belt and Road projects across Africa, contributing to initiatives in Gabon, Guinea, Cameroon, South Africa, and Morocco.',
            ],
            [
                'name'  => 'Mr. James Wang',
                'title' => 'CEO (China)',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=379,fit=crop/ALpeJ1OkE5HqbP9Z/james-mp8Wovy5vRhoO2zJ.png',
                'bio'   => 'Mr. James Wang, CEO for China at Amerigroup International, steers the company\'s strategic vision and operations in the Chinese market. With over 15 years of experience at Fortune 500 companies and leading Chinese corporations, he excels in managing government relations and partnering with state-owned enterprises. He has overseen transactions exceeding $10 billion and played a key role in Belt and Road projects across several African countries.',
            ],
            [
                'name'  => 'Mr. Roberto Compeán Woodworth',
                'title' => 'CFO (Mexico), Amerigroup International | CFO & Co-founder, AmerigroupLNG',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=372,fit=crop/ALpeJ1OkE5HqbP9Z/robert-YKb3v622g7cVO74g.png',
                'bio'   => 'Mr. Roberto Compeán Woodworth, CFO of Amerigroup International for the Mexico region and co-founder of AmerigroupLNG, drives the company\'s financial strategy. His leadership includes Chief Sales Officer at Mexico\'s National Lottery and CFO for Bestel and Cablevision Monterrey — key Televisa subsidiaries. His tenure at BBVA Bank, including advanced training in Madrid, solidified his expertise in finance. He earned his Bachelor\'s in Business Administration from ITAM University.',
            ],
            [
                'name'  => 'Mr. Peter Pang',
                'title' => 'CFO (CGA/CFA) Global',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=384,fit=crop/ALpeJ1OkE5HqbP9Z/peter-d951PKBvrNHxeQ8g.png',
                'bio'   => 'Mr. Peter Pang, CFO of Amerigroup International, is a distinguished financial leader with over 30 years of industry experience. As a former partner at KPMG Vancouver and a Chartered Professional Accountant in Canada, he brings deep expertise in auditing, financial management, and mergers and acquisitions. His strategic leadership in managing multi-billion-dollar enterprises has earned him a global reputation.',
            ],
            [
                'name'  => 'Mr. Victor Manuel Villanueva Rivera',
                'title' => 'Managing Director',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=372,fit=crop/ALpeJ1OkE5HqbP9Z/victor-A1aPlwDLWMu8kvkD.png',
                'bio'   => 'Mr. Victor Manuel Villanueva Rivera is a seasoned executive with over 40 years in the automotive industry. Previous roles include Managing Director at Jetour Motors and FIAT Mexico, Sales Director at Hertz-AVASA, and CEO & Managing Director of Mitsubishi Motors Mexico. He holds a Master\'s degree in Quality Engineering and a Bachelor\'s in Industrial Engineering.',
            ],
            [
                'name'  => 'Ms. Vanessa Muñoz',
                'title' => 'Business Development Director',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=372,fit=crop/ALpeJ1OkE5HqbP9Z/vanessa-mePxXv6jlrub690Q.png',
                'bio'   => 'Ms. Vanessa Muñoz acts a key role in developing new business opportunities. She has successfully owned and operated various businesses in Mexico and the U.S. Previously Real Estate Commercial and Leasing Manager for Liverpool, and at Alsea facilitated strategic negotiations with major developers. Holds a Bachelor\'s in International Relations from Tecnologico de Monterrey.',
            ],
            [
                'name'  => 'Ms. Liviere Galván',
                'title' => 'Commercial Director',
                'img'   => 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,h=372,fit=crop/ALpeJ1OkE5HqbP9Z/livy-Awv45MBG40IBBwLM.png',
                'bio'   => 'Ms. Liviere Galván transitioned from Sales Manager to Commercial Director, driving the company\'s sales strategy, new business development, and international client expansion. Prior to Amerigroup, she served as Director of Sales and Marketing at Dronamex for over five years. Holds both an MSc and Bachelor\'s degree in Marketing.',
            ],
        ]; ?>
        <div class="team-grid">
            <?php foreach($team as $m): ?>
            <div class="team-card">
                <div class="team-card-photo">
                    <img src="<?php echo esc_url($m['img']); ?>" alt="<?php echo esc_attr($m['name']); ?>" loading="lazy">
                </div>
                <div class="team-card-body">
                    <h3><?php echo esc_html($m['name']); ?></h3>
                    <div class="team-title"><?php echo esc_html($m['title']); ?></div>
                    <p><?php echo esc_html($m['bio']); ?></p>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>
</section>

<?php get_footer(); ?>
