<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * Template Name: Projects — v2
 * Fixes vs v1:
 *  - Solar/Wind image corrected to exact Unsplash windmill photo from live (photo-1710075707220)
 *  - "Long-Term Operational Benefits" paragraph added to EV Conversion section — matches live
 *  - LNG section image corrected to lng-vessel-3 (webp) from live
 *  - Image between Solar and Green Energy: h2-truck-station-2 (exact from live)
 *  - Image between Green Energy and EV: truck-1 (exact from live)
 */
get_header(); ?>

<section class="page-hero">
    <div class="page-hero-video">
        <div class="page-hero-fallback" style="background-image:url('https://images.pexels.com/videos/2078401/free-video-2078401.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920');"></div>
        <video autoplay muted loop playsinline
               poster="https://images.pexels.com/videos/2078401/free-video-2078401.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920">
            <source src="https://videos.pexels.com/video-files/2078401/2078401-uhd_3840_2160_30fps.mp4" type="video/mp4">
        </video>
    </div>
    <div class="page-hero-overlay"></div>
    <div class="container">
        <div class="page-hero-content">
            <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Home','amerigroup'); ?></a> &rsaquo; <?php esc_html_e('Projects','amerigroup'); ?></p>
            <h1><?php esc_html_e('Sustainability Solutions','amerigroup'); ?></h1>
            <p class="page-hero-sub"><?php esc_html_e('Innovative solutions to zero-emission energy, efficient infrastructure, advanced water treatment, hydrogen and ammonia production, and power grid enhancements for environmental protection.','amerigroup'); ?></p>
        </div>
    </div>
</section>

<!-- SECTION HEADER -->
<section class="section">
    <div class="container">
        <div class="text-center" style="margin-bottom:56px;">
            <span class="section-label"><?php esc_html_e('Our Projects','amerigroup'); ?></span>
            <h1 class="section-title"><?php esc_html_e('Sustainability Solutions','amerigroup'); ?></h1>
            <p class="section-lead"><?php esc_html_e('Innovative solutions to Zero-emission energy, efficient infrastructure, advanced water treatment, hydrogen and ammonia production, and power grid enhancements for environmental protection.','amerigroup'); ?></p>
        </div>

        <!-- SOLAR & WIND — uses exact Unsplash windmill image from live site -->
        <div class="tech-item">
            <div class="tech-item-img">
                <!-- EXACT image from live: photo-1710075707220-103d36c97ec6 -->
                <img src="https://images.unsplash.com/photo-1710075707220-103d36c97ec6?auto=format&fit=crop&w=612&h=564"
                     alt="<?php esc_attr_e('a bunch of windmills that are standing in the grass','amerigroup'); ?>" loading="lazy">
            </div>
            <div class="tech-item-body">
                <span class="section-label"><?php esc_html_e('Renewable Energy','amerigroup'); ?></span>
                <h2><strong><?php esc_html_e('Solar and Wind Power Generation','amerigroup'); ?></strong></h2>
                <p><?php esc_html_e('Amerigroup is at the forefront of integrating renewable energy sources into our clean energy solutions. Our solar and wind power generation projects are designed to harness the abundant natural resources available, converting them into sustainable electricity. This electricity is then used to produce hydrogen and ammonia, creating a continuous cycle of clean energy production. Our services include:','amerigroup'); ?></p>
                <ul style="margin-top:16px;list-style:none;display:flex;flex-direction:column;gap:10px;">
                    <?php foreach([
                        ['Solar Power Plants',                    'Developing and managing large-scale solar power facilities that convert sunlight into electricity.'],
                        ['Wind Farms',                            'Establishing and operating wind farms that capture wind energy and convert it into electrical power.'],
                        ['Electrolysis for Hydrogen Production',  'Using renewable electricity to split water into hydrogen and oxygen, providing a sustainable source of hydrogen.'],
                        ['Ammonia Production',                    'Utilizing hydrogen produced from renewable sources to create ammonia, a key component for energy storage and agricultural applications.'],
                    ] as $li): ?>
                    <li style="padding:12px 16px;background:var(--ag-offwhite);border-radius:6px;border-left:3px solid var(--ag-blue);font-size:.9rem;color:var(--ag-muted);">
                        <strong style="color:var(--ag-text);"><?php echo esc_html($li[0]); ?>:</strong> <?php echo esc_html($li[1]); ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- GREEN ENERGY SOLUTIONS — with h2-truck-station image -->
<section class="section section-alt">
    <div class="container">
        <div class="tech-item reverse">
            <div class="tech-item-img">
                <!-- EXACT image from live: h2-truck-station-2 -->
                <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=553,fit=crop/ALpeJ1OkE5HqbP9Z/h2-truck-station-2-ALpoNRMgwRHjQ9bQ.jpg"
                     alt="<?php esc_attr_e('Hydrogen truck station','amerigroup'); ?>" loading="lazy">
            </div>
            <div class="tech-item-body">
                <span class="section-label"><?php esc_html_e('Green Energy','amerigroup'); ?></span>
                <h2><strong><?php esc_html_e('Green Energy Solutions','amerigroup'); ?></strong></h2>
                <?php foreach([
                    ['Hydrogen Development',            'Leading in zero-emission hydrogen generation and production. Our state-of-the-art facilities and research initiatives focus on optimizing hydrogen production processes to meet growing demand.'],
                    ['Hydrogen and Ammonia Production',  'Utilizing advanced technology for sustainable energy solutions. We produce high-purity hydrogen and ammonia for industrial, transportation, and energy storage applications.'],
                    ['Power Grid Projects',              "Enhancing Mexico's national power grid with innovative engineering, ensuring stable and efficient energy distribution."],
                ] as $item): ?>
                <p style="margin-top:14px;"><strong><?php echo esc_html($item[0]); ?>:</strong> <?php echo esc_html($item[1]); ?></p>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</section>

<!-- EV CONVERSION — with truck-1 image + Long-Term Operational Benefits -->
<section class="section">
    <div class="container">
        <div class="tech-item">
            <div class="tech-item-img">
                <!-- EXACT image from live: truck-1 -->
                <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=553,fit=crop/ALpeJ1OkE5HqbP9Z/truck-1-YKbrnR54Jlc0OQzq.jpg"
                     alt="<?php esc_attr_e('EV truck','amerigroup'); ?>" loading="lazy">
            </div>
            <div class="tech-item-body">
                <span class="section-label"><?php esc_html_e('E-Mobility','amerigroup'); ?></span>
                <h2><strong><?php esc_html_e('EV Conversion','amerigroup'); ?></strong></h2>
                <p><?php esc_html_e('We specialize in the conversion of Class 5 and 8 trucks from diesel to electric using cutting-edge e-axle technology. Our EV conversion services help reduce diesel consumption and pollution while significantly increasing travel range, up to 1,300 miles. Our notable clients include: Staples, UPS, FedEx, Kenworth etc.','amerigroup'); ?></p>
                <!-- MISSING in v1 — present on live site -->
                <p style="margin-top:14px;"><strong><?php esc_html_e('Long-Term Operational Benefits:','amerigroup'); ?></strong> <?php esc_html_e('Evaluating the financial and environmental benefits of hydrogen trucks and EV conversions, including cost savings, reduced maintenance expenses, and improved sustainability.','amerigroup'); ?></p>
            </div>
        </div>
    </div>
</section>

<!-- LNG & LPG — with lng-vessel-3 image -->
<section class="section section-alt">
    <div class="container">
        <div class="tech-item reverse">
            <div class="tech-item-img">
                <!-- EXACT image from live: lng-vessel-3 webp -->
                <img src="https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=768,h=553,fit=crop/ALpeJ1OkE5HqbP9Z/lng-vessel-3-mePnoz6ER1f3VkZr.webp"
                     alt="<?php esc_attr_e('LNG vessel','amerigroup'); ?>" loading="lazy">
            </div>
            <div class="tech-item-body">
                <span class="section-label"><?php esc_html_e('LNG & LPG','amerigroup'); ?></span>
                <h2><strong><?php esc_html_e('LNG & LPG Infrastructure and Logistics','amerigroup'); ?></strong></h2>
                <p><?php esc_html_e("Amerigroup is a trusted partner in clean fuel mobility, energy transition logistics, and regasification infrastructure across the Americas and beyond. Our long-standing presence in U.S. – Mexico LNG and LPG corridors provides the foundation for scalable, reliable energy solutions:",'amerigroup'); ?></p>
                <?php foreach([
                    ['LNG and LPG Transportation',          'End-to-end transport solutions by ship, truck, ISO container, and pipeline, ensuring secure delivery across borders'],
                    ['Onshore Regasification',               'Localized conversion of LNG back to natural gas for utilities, factories, and power grids'],
                    ['FSRU (Floating Storage and Regasification Units)', 'Rapid-deployment offshore terminals that provide LNG import and regas capacity without the need for land-based infrastructure. Ideal for port cities, island nations, and countries facing land constraints or urgent energy needs'],
                    ['Marine Bunkering',                     'Supplying LNG as a cleaner fuel for maritime fleets'],
                    ['Comprehensive LNG Chain Management',   'From export and storage to regasification and dispatch, we offer full-scope LNG handling — pump, load, move, vaporize, and deliver, all with efficiency and safety at scale'],
                    ['Small-Scale Distribution',             'Delivering LNG and LPG to off-grid, rural, or remote industrial sites'],
                ] as $item): ?>
                <p style="margin-top:10px;font-size:.9rem;color:var(--ag-muted);">
                    <strong style="color:var(--ag-text);"><?php echo esc_html($item[0]); ?>:</strong> <?php echo esc_html($item[1]); ?>
                </p>
                <?php endforeach; ?>
                <!-- DOE approval — italic on live -->
                <p style="margin-top:20px;padding:16px;background:var(--ag-blue-light);border-radius:8px;font-size:.88rem;font-style:italic;color:var(--ag-blue-dark);">
                    <?php esc_html_e('The U.S. Department of Energy (DOE) has approved AmerigroupLNG to export approximately 4.6 billion cubic feet (Bcf) of liquefied natural gas (LNG) from the United States. This significant achievement underscores our commitment to providing high-quality energy solutions and expanding our global reach.','amerigroup'); ?>
                </p>
            </div>
        </div>
    </div>
</section>

<?php get_footer(); ?>
