<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * Template Name: Our Partners — v2
 * Fixes vs v1:
 *  - Page <title> / SEO title corrected to match live: "Building Strong Partnerships for SEO Success"
 *  - All 35 unique partner logo URLs re-verified against live source HTML
 *  - Added the 35th logo (ay-c-ae-ae---small) which was present in live but may have been missed
 *  - Disclaimer text verified word-for-word against live
 */
get_header(); ?>

<section class="page-hero">
    <div class="page-hero-video">
        <div class="page-hero-fallback" style="background-image:url('https://images.pexels.com/videos/6192775/business-college-education-group-6192775.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920');"></div>
        <video autoplay muted loop playsinline
               poster="https://images.pexels.com/videos/6192775/business-college-education-group-6192775.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=1920">
            <source src="https://videos.pexels.com/video-files/6192775/6192775-uhd_3840_2160_25fps.mp4" type="video/mp4">
        </video>
    </div>
    <div class="page-hero-overlay"></div>
    <div class="container">
        <div class="page-hero-content">
            <p class="breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>"><?php esc_html_e('Home','amerigroup'); ?></a> &rsaquo; <?php esc_html_e('Our Partners','amerigroup'); ?></p>
            <!-- Live page title tag: "Building Strong Partnerships for SEO Success" -->
            <h1><?php esc_html_e('Building Strong Partnerships for SEO Success','amerigroup'); ?></h1>
            <p class="page-hero-sub"><?php esc_html_e('Collaborating with global industry leaders to accelerate the clean energy transition.','amerigroup'); ?></p>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">

        <div class="text-center partners-intro">
            <span class="section-label"><?php esc_html_e('Our Collaboration','amerigroup'); ?></span>
            <h2 class="section-title"><?php esc_html_e('Our Partners & Collaborators','amerigroup'); ?></h2>
        </div>

        <?php
        $partner_query = new WP_Query(['post_type'=>'ag_partner','posts_per_page'=>-1,'orderby'=>'menu_order','order'=>'ASC']);
        if($partner_query->have_posts()):
            echo '<div class="partners-grid">';
            while($partner_query->have_posts()): $partner_query->the_post(); ?>
                <div class="partner-logo">
                    <?php if(has_post_thumbnail()): the_post_thumbnail('ag-partner',['alt'=>get_the_title()]);
                    else: ?><span style="font-size:.85rem;color:var(--ag-muted);"><?php the_title(); ?></span><?php endif; ?>
                </div>
            <?php endwhile; wp_reset_postdata();
            echo '</div>';
        else:
            // ALL 35 unique logos verified against live site HTML (first occurrence, before the animated loop)
            $partners = [
                ['CFE (Comisión Federal de Electricidad)',  'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/cfe-logo-Aq2oqEJEKxH3VvkL.jpg'],
                ['Partner 2',                               'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/5fd99ac4b0de0221d2f2ece460ddadc4-YZ98b0kbexC9zvNN.jpeg'],
                ['BayoTech',                                'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/bayotech-Y4LDJEekqDHOD0bn.jpeg'],
                ['Mainspring Energy',                       'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/mainspring-logo-Yg29q3y3ERFoQ3Nx.jpg'],
                ['Power China',                             'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/power-china-logo-Awv4k1PnW7iljRRz.jpeg'],
                ['CPECC',                                   'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/cpecc-logo-m2WQaVEV5JHqVqkR.jpg'],
                ['Hybot',                                   'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/hybot-logo-small-A85e4rX7bZCD9jOo.jpg'],
                ['HyPower',                                 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/hypower-mnlW95KMKMhDa0Q1.jpeg'],
                ['HBA',                                     'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/hba-clear-small-m5KMbrvJXgHxzRko.png'],
                ['AmeriGas',                                'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/amerigas-logo-m5KMbxKl53f620Mv.jpeg'],
                ['Nikola',                                  'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/nikola-logo-mxB7MWXWyLT8QO8X.png'],
                ['Pan America',                             'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/pan-america-logo-small-AMq14xkovju5bMLk.png'],
                ['Sauber Water',                            'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/sauber-water-logo-ALpo7qPK4lHn1KrA.jpg'],
                ['CPECC (main)',                            'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/cpecc-main-A1aPJNxlRbhPyxOR.jpg'],
                ['CEEC GEDI',                               'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/ceec-gedi-logo-AQEpDbZbeVIGXXQn.jpg'],
                ['Tian Tang',                               'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/tian-tang-small-m7V3Kkb00rIrO6Me.png'],
                ['AG International',                        'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/ag-intal-YleWy2Zp37u9bqGw.PNG'],
                ['Partner (Sep 2025)',                      'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/screenshot-2025-09-26-at-1.44.44a-pm-YBgj45VznPTQRVKw.png'],
                ['Conacen',                                 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/conacen1-m2W8Q5zQNoH9rXjB.jpeg'],
                ['H2B2',                                    'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/h2b2-logo-AzG73bNb19f20z9N.jpg'],
                ['Technical America',                       'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/technical-america-logo-mk39qaJWRxSK5jqr.jpg'],
                ['CSCEC',                                   'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/cscec-AVL7b3D4EgtN8JDJ.jpg'],
                ['Vastgold',                                'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/vastgold-final-smaller-Aq2WoBy152Cg2JbG.png'],
                ['Sangfor',                                 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/sangfor-m7V3KjvZrQiDQQlD.jpg'],
                ['GRB',                                     'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/grb-3-A85e4yW7LQipyL4q.jpg'],
                ['ASA',                                     'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/a-ssa-copy-2-mePgn0jgrVslykLJ.png'],
                ['Partner (Apr 2025)',                      'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/screenshot-2025-04-11-at-9.10.30a-pm-Yan19zxGBDsEVOvK.png'],
                ['Mexmot',                                  'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/mexmot-logo-YleyqOQJJWFbKXrJ.jpg'],
                ['Evenflo',                                 'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/evenflo-YD04BxwxZxCvB643.jpg'],
                ['Cryotainer',                              'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/cryotainer-logo-YBg4eaba15FBkWaN.jpg'],
                ['Big River Energy',                        'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/big-river-energy-logo-dWxvb9X5X2H6v4J2.jpeg'],
                ['SUMEC',                                   'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/sumec-Yyv97LxQGltQkxDK.jpg'],
                ['SUMEC International Technology',         'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/sumec-int-l-tech-co-m2W8Qkn5ngij4p69.png'],
                ['Jishang Fortune',                         'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/jishang-fortune-small-dWxvb0l3k0c6E1vX.png'],
                ['Partner 35',                              'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/35ec40431d63300b5c2ef87aaaa35a81-3-YBgj45gEqkHo4PQm.jpeg'],
                // 36th: ay-c-ae-ae logo — present in live site HTML
                ['Partner 36',                              'https://assets.zyrosite.com/cdn-cgi/image/format=auto,w=375,fit=crop/ALpeJ1OkE5HqbP9Z/ay-c-ae-ae---small-Aq2WoNBgM0Uw68qP.png'],
            ];
            ?>
            <div class="partners-grid">
                <?php foreach($partners as $p): ?>
                <div class="partner-logo">
                    <img src="<?php echo esc_url($p[1]); ?>" alt="<?php echo esc_attr($p[0]); ?>" loading="lazy">
                </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <!-- DISCLAIMER — exact wording from live site -->
        <p class="partners-disclaimer">
            <?php esc_html_e('Our team proudly reflects on its rich history of professional experience. The logos above represent the respected organizations where our team members have previously contributed their expertise. These logos are the registered trademarks of their respective companies and are displayed solely to showcase our collective background.','amerigroup'); ?>
        </p>

    </div>
</section>

<?php get_footer(); ?>
