<?php
/**
 * ============================================================================
 * COPYRIGHT (c) 2023-2025 Amerigroup International. All rights reserved.
 * ============================================================================
 * Owner   : Amerigroup International
 * Website : https://www.amerigroupint.net
 * Offices : Hong Kong | Beijing, China | Vancouver, Canada
 *
 * SOURCE ATTRIBUTION
 * ------------------
 * All content in this theme (text, images, branding, team profiles, partner
 * logos, product descriptions) was sourced exclusively from the original
 * Amerigroup International website: https://www.amerigroupint.net
 *
 * This file was generated by mirroring and converting the live site at
 * https://www.amerigroupint.net into a WordPress theme. No content was
 * invented or altered — all copy and assets remain the sole intellectual
 * property of Amerigroup International.
 *
 * LICENSE: PROPRIETARY & CONFIDENTIAL
 * ------------------------------------
 * Use of this file is restricted to Amerigroup International's own
 * WordPress installation. Redistribution or third-party use is prohibited
 * without express written permission from Amerigroup International.
 * ============================================================================
 */
/**
 * template-parts/contact-cta.php — v2
 * CTA text verified against live: "Join Us in Building the Energy Systems of Tomorrow"
 * Field labels verified: "Contact us for energy solutions*", "Email*", "Enquiry*"
 */
?>
<section class="cta-section" id="contact">
    <div class="container">
        <h2><?php esc_html_e('Join Us in Building the Energy Systems of Tomorrow','amerigroup'); ?></h2>
        <p><?php esc_html_e('Leading provider of zero-emission energy solutions.','amerigroup'); ?></p>

        <form class="contact-form" id="ag-contact-form" novalidate>
            <?php wp_nonce_field('ag_contact_nonce','ag_nonce_field'); ?>

            <input type="text" id="contact_name" name="contact_name"
                   placeholder="<?php esc_attr_e('Contact us for energy solutions *','amerigroup'); ?>" required>

            <input type="email" id="contact_email" name="contact_email"
                   placeholder="<?php esc_attr_e('Email *','amerigroup'); ?>" required>

            <textarea id="contact_enquiry" name="contact_enquiry"
                      placeholder="<?php esc_attr_e('Enquiry *','amerigroup'); ?>" required></textarea>

            <div id="ag-form-message" style="display:none;padding:12px;border-radius:6px;text-align:center;"></div>

            <button type="submit" class="btn-submit"><?php esc_html_e('Submit','amerigroup'); ?></button>
        </form>
    </div>
</section>
